# Generated by Django 5.1.7 on 2025-04-28 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sales_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('For Lease', 'For Lease')], default='For Sale', max_length=20)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Land', 'Land'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Retail', 'Retail'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Hotel', 'Hotel'), ('Villa', 'Villa')], default='Apartment', max_length=20)),
                ('photo_main', models.ImageField(upload_to='listing_photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='listing_photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='listing_photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='listing_photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realtor', models.ForeignKey(limit_choices_to={'role': 'realtor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
