# Generated by Django 5.1.7 on 2025-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccount_address_useraccount_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_realtor',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('realtor', 'Realtor'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
