# Generated by Django 5.1.7 on 2025-04-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_useraccount_is_realtor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
