# Generated by Django 5.1.7 on 2025-04-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraccount_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
